# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'messaging-app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for messaging-app

  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'IQKeyboardManagerSwift'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'

end
